CONFIG_PROFILES = {
    "5x5_center_off": {
        "board_size": 5,
        "center_wall": False,
        "komi": 0,
        "use_fast_env": True,
        "use_liberty_features": True,
        "liberty_bins": 2,
        "use_last_moves": True,
        "num_res_blocks": 3,
        "num_channels": 64,
        "num_simulations": 100,
        "c_puct": 2.0,
        "dirichlet_alpha": 0.3,
        "dirichlet_epsilon": 0.25,
        "playout_full_prob": 0.25,
        "playout_full_cap": 120,
        "playout_fast_cap": 20,
        "infer_batch_size": 64,
        "infer_timeout": 0.001,
        "eval_infer_batch_size": 64,
        "eval_infer_timeout": 0.001,
        "mcts_eval_batch_size": 1,
        "mcts_profile": False,
        "mcts_profile_every": 0,
        "temperature_schedule": {5: 1.0, 10: 0.5},
        "use_forced_playouts": True,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 100,
        "games_per_iteration": 500,
        "batches_per_iteration": 300,
        "eval_games": 50,
        "save_interval": 5,
        "temperature_threshold": 10,
        "fresh_start": True,
        "batch_size": 256,
        "buffer_size": 100000,
        "checkpoint_dir": None
    },
    "5x5_center_on": {
        "board_size": 5,
        "center_wall": True,
        "komi": 0,
        "use_fast_env": False,
        "use_liberty_features": True,
        "liberty_bins": 2,
        "use_last_moves": False,
        "num_res_blocks": 3,
        "num_channels": 64,
        "num_simulations": 70,
        "c_puct": 2.0,
        "dirichlet_alpha": 0.3,
        "dirichlet_epsilon": 0.25,
        "playout_full_prob": 0.25,
        "playout_full_cap": 600,
        "playout_fast_cap": 100,
        "infer_batch_size": 256,
        "infer_timeout": 0.05,
        "eval_infer_batch_size": 64,
        "eval_infer_timeout": 0.005,
        "mcts_eval_batch_size": 1,
        "mcts_profile": False,
        "mcts_profile_every": 0,
        "temperature_schedule": {5: 1.0, 10: 0.5},
        "use_forced_playouts": False,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 500,
        "games_per_iteration": 300,
        "batches_per_iteration": 300,
        "eval_games": 20,
        "save_interval": 5,
        "temperature_threshold": 20,
        "fresh_start": False,
        "batch_size": 256,
        "buffer_size": 400000,
        "checkpoint_dir": None
    },
    "7x7_center_on": {
        "board_size": 7,
        "center_wall": True,
        "komi": 3,
        "benchmark_interval": 0,
        "network_head": "conv",
        "freeze_backbone": False,
        "use_fast_env": True,
        "use_liberty_features": True,
        "liberty_bins": 1,
        "use_last_moves": True,
        "num_res_blocks": 5,
        "num_channels": 96,
        "num_simulations": 300,
        "c_puct": 1.7,
        "dirichlet_alpha": 0.2,
        "dirichlet_epsilon": 0.12,
        "playout_full_prob": 0.3,
        "playout_full_cap": 350,
        "playout_fast_cap": 70,
        "infer_batch_size": 16,
        "infer_timeout": 0.0002,
        "eval_infer_batch_size": 32,
        "eval_infer_timeout": 0.0002,
        "mcts_eval_batch_size": 4,
        "mcts_profile": False,
        "mcts_profile_every": 0,
        "temperature_schedule": {5: 0.8, 10: 0.4, 11:0.1},
        "use_forced_playouts": True,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 1500,
        "games_per_iteration": 500,
        "batches_per_iteration": 200,
        "eval_games": 10,
        "save_interval": 5,
        "selfplay_record_interval": 10,
        "selfplay_record_dir": "logs/selfplay_records/board_7/center_wall_on/b5c96",
        "temperature_threshold": 20,
        "batch_size": 256,
        "buffer_size": 50000,
        "ownership_loss_weight": 1,
        "ownership_loss_weight_capture": 0.5,
        "win_loss_weight": 0.2,
        "win_type_loss_weight": 0.2,
        "cache_debug_samples": 50,
        "cache_max_entries": 500000,
        "train_buffer_min_factor": 0.2,
        "cache_enabled": False,       # selfplay/benchmark 캐시 off
        "eval_cache_enabled": False,  # eval 캐시 off
        "eval_opponent_async": True,   # best도 async/GPU

        "fresh_start": False,
        "checkpoint_dir": "checkpoints/board_7/center_wall_on/b5c96"
    },
    "9x9_center_on": {
        "board_size": 9,
        "center_wall": True,
        "komi": 3,
        "network_head": "conv",
        "freeze_backbone_blocks": 5,
        "freeze_backbone_input": True,
        "freeze_heads": True,
        "freeze_schedule": {1: 5, 50: "unfreeze"},
        "freeze_head_schedule": {1: True, 50: False},
        "init_checkpoint": "checkpoints/board_7/center_wall_on/b5c96/alphazero_latest.pt",
        "benchmark_interval": 0,
        "use_fast_env": True,
        "use_liberty_features": True,
        "liberty_bins": 1,
        "use_last_moves": True,
        "num_res_blocks": 8,
        "num_channels": 96,
        "num_simulations": 500,
        "c_puct": 1.7,
        "dirichlet_alpha": 0.2,
        "dirichlet_epsilon": 0.15,
        "playout_full_prob": 0.3,
        "playout_full_cap": 500,
        "playout_fast_cap": 120,
        "infer_batch_size": 32,
        "infer_timeout": 0.0001,
        "eval_infer_batch_size": 32,
        "eval_infer_timeout": 0.0001,
        "mcts_eval_batch_size": 4,
        "mcts_profile": False,
        "mcts_profile_every": 0,
        "temperature_schedule": {3: 0.8, 6: 0.6, 10: 0.4, 14: 0.2, 15:0.1},
        "use_forced_playouts": True,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 2000,
        "games_per_iteration": 500,
        "batches_per_iteration": 200,
        "eval_games": 30,
        "save_interval": 5,
        "selfplay_record_interval": 10,
        "selfplay_record_dir": "logs/selfplay_records/board_9/center_wall_on/b8c96",
        "temperature_threshold": 20,
        "fresh_start": False,
        "batch_size": 256,
        "buffer_size": 100000,
        "ownership_loss_weight": 0.5,
        "ownership_loss_weight_capture": 0.2,
        "win_loss_weight": 0.1,
        "win_type_loss_weight": 0.1,
        "cache_debug_samples": 1,
        "cache_max_entries": 500000,
        "train_buffer_min_factor": 0.5,
        "cache_enabled": False,       # selfplay/benchmark 캐시 off
        "eval_cache_enabled": False,  # eval 캐시 off
        "eval_opponent_async": True,   # best도 async/GPU

        "checkpoint_dir": "checkpoints/board_9/center_wall_on/b8c96"

    },
    "6x6_center_off": {
        "board_size": 6,
        "center_wall": False,
        "komi": 0,
        "use_fast_env": False,
        "use_liberty_features": True,
        "liberty_bins": 2,
        "use_last_moves": False,
        "num_res_blocks": 4,
        "num_channels": 64,
        "num_simulations": 100,
        "c_puct": 2.0,
        "dirichlet_alpha": 0.3,
        "dirichlet_epsilon": 0.25,
        "playout_full_prob": 0.4,
        "playout_full_cap": 180,
        "playout_fast_cap": 30,
        "infer_batch_size": 64,
        "infer_timeout": 0.001,
        "eval_infer_batch_size": 64,
        "eval_infer_timeout": 0.001,
        "mcts_eval_batch_size": 1,
        "mcts_profile": False,
        "mcts_profile_every": 0,
        "temperature_schedule": {7: 1.0, 14: 0.5},
        "use_forced_playouts": True,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 200,
        "games_per_iteration": 300,
        "batches_per_iteration": 400,
        "eval_games": 20,
        "save_interval": 5,
        "temperature_threshold": 20,
        "fresh_start": False,
        "batch_size": 128,
        "buffer_size": 100000,
        "checkpoint_dir": None
    },
    "4x4_center_off": {
        "board_size": 4,
        "center_wall": False,
        "komi": 0,
        "use_fast_env": True,
        "use_liberty_features": True,
        "liberty_bins": 1,
        "use_last_moves": False,
        "num_res_blocks": 3,
        "num_channels": 48,
        "num_simulations": 100,
        "c_puct": 2.0,
        "dirichlet_alpha": 0.3,
        "dirichlet_epsilon": 0.25,
        "playout_full_prob": 0.5,
        "playout_full_cap": 150,
        "playout_fast_cap": 30,
        "infer_batch_size": 32,
        "infer_timeout": 0.001,
        "eval_infer_batch_size": 32,
        "eval_infer_timeout": 0.001,
        "mcts_eval_batch_size": 2,
        "mcts_profile": False,
        "mcts_profile_every": 50,
        "temperature_schedule": {3: 1.0, 6: 0.5},
        "use_forced_playouts": True,
        "use_policy_target_pruning": True,
        "forced_playout_k": 2.0,
        "num_iterations": 100,
        "games_per_iteration": 500,
        "batches_per_iteration": 300,
        "eval_games": 50,
        "save_interval": 5,
        "temperature_threshold": 5,
        "fresh_start": False,
        "batch_size": 128,
        "buffer_size": 100000,
        "checkpoint_dir": None
    }
}


def list_profiles():
    return sorted(CONFIG_PROFILES.keys())


def get_profile(profile_name):
    if profile_name not in CONFIG_PROFILES:
        raise KeyError(f"Unknown profile: {profile_name}")
    return dict(CONFIG_PROFILES[profile_name])
